## What is Pytorch?

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[ 1.5125e-34,  4.5591e-41,  1.5125e-34],
        [ 4.5591e-41,         nan,  0.0000e+00],
        [ 7.6194e+31,  1.5564e+28,  1.8484e+31],
        [ 1.8370e+25,  1.4603e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28]])


In [9]:
x = torch.tensor(1)
print(x.type())
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    print("GPU tensor has device attr")
    print(y)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))
    print(z.type())

torch.LongTensor
GPU tensor has device attr
tensor(1, device='cuda:0')
tensor(2, device='cuda:0')
tensor(2., dtype=torch.float64)
torch.cuda.LongTensor


## Autograd

In [12]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.type())

tensor([[ 1.,  1.],
        [ 1.,  1.]])
torch.FloatTensor


In [13]:
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [14]:
print(y.grad_fn)

In [17]:
z = y * y * 3
out = z.mean()
print(z, out)
print(z.requires_grad)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)
True


In [18]:
out.backward()

In [19]:
print(x.grad) # d(out) / dx = 1/4 * 6y * 1 = 18/4 = 4.5  

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [20]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([-725.0751, -340.1002, -609.2215])


In [24]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
# y.backward()
# grad can be implicitly created only for scalar outputs 과 같은 RuntimeError
print(x.grad)

tensor([  204.8000,  2048.0000,     0.2048])


In [22]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
